stages:
 - test
 - build
    
test_stage:
    except:
     changes:
       - manifest/*
    stage: test
    image: golang:latest
    script:
        - go test -v ./pkg/test_apis/add_test.go
        - go test -v ./pkg/test_apis/get_test.go
        - go test -v ./pkg/test_apis/update_test.go
        - go test -v ./pkg/test_apis/delete_test.go
        - go build
        - ls
build_stage:
    except:
     changes:
       - manifest/*
    stage: build
    image: docker:git
    services:
     - docker:dind
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    script:
        - docker build -t mangaaldochub/store-api:$CI_COMMIT_SHA .
        - docker push  mangaaldochub/store-api:$CI_COMMIT_SHA  
