apiVersion: v1
kind: Namespace
metadata:
  name: store-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app
  namespcae: store-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-app
  template:
    metadata:
      labels:
        app: store-app
    spec:
      containers:
        - name: store-app
          image:cd 
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0  # Run as root user
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: store-app-service
   namespcae: store-api
spec:
  selector:
    app: store-app
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 80  # Port on the pods
  type: ClusterIP





