apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: monitoring
  labels:
   controller: grafana-operator
spec:
  containers:
  - name: nginx
    image: nginx:1.14.1
    ports:
    - containerPort: 80
